### PR TITLE
Fix for using attribute "configFile" along with additional properties

### PR DESCRIPTION
**Pull request by data219**
Did a fix for using attribute "configFile" along with additional properties.
Now always uses the generated tmp config file.
Problem was, it generated one, which is a merge from the file from the attribute and the additional properties, but then used only the file from the attribute instead of the generated one to execute doxygen.

### CODE REVIEW

**Comment by akkumar** [comment]
Sorry for the delayed reply. 

So, I quickly did a diff (ignoring whitespace) here: 

 diff -w ./src/org/doxygen/tools/DoxygenTask.java /tmp/ant-doxygen/src/org/doxygen/tools/DoxygenTask.java
166c166
  <     proc.executeDoxygenConfig(configFilename);

> ```
>     proc.executeDoxygenConfig(CONFIG_FILE);
> ```

Seems like the patch replaces configFileName with CONFIG_FILE  (the default one).  ? 

Would not that always ignore the overridden settings otherwise ?

**Comment by vasvir** [comment]
Let me shed some light into the request. I have the exact same patch data219 mentions applied. The patch is an actual BUGFix:

The use case is the following:

I have many projects. I have one common file for all. I want to override some options per project with ant properties.

ant-doxygen so far covers these use cases
a) use only config file (no properties from antfile (build.xml))
b) use only properties specified in the antfile

What the data219's does is:

c) take the supplied configfile and override specific properties define in the antfile (build.xml)

The patch is correct because in

``` java
DoxygenConfig.writeDoxygenConfig(final String theConfigFilename) 
...
        SortedMap<String, String> map = readDoxygenConfig(theConfigFilename);
        cascadeDoxygenConfig(map);
        try {
            ps = new PrintStream(
                     new FileOutputStream(DoxygenTask.CONFIG_FILE));  
```

so you are reading from the supplied config file, you are overriding the properties but you are writing to the CONFIG_FILE so it is the CONFIG_FILE you need to execute. It may be a little bit confusing but the patch would be the minimum fix (if there were no white space changes).

```
Vassilis
```

**Comment by akkumar** [comment]
Seems like the diff is out of date , as I cannot merge the pull request. 

If it can be resubmitted, I can take it in ?

**Comment by vasvir** [comment]
I think that you can close this issue and the relevant (older) pull request now.

**Pull request closed without merging**
